# Change these first
owner: tecnicaformazionesicurezza # Your GitHub organization or username, where this repository lives
repo: uptime-jarvis # The name of this repository

sites:
  - name: Jarvis
    url: https://jarvis.gtsu.org
 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-jarvis
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jarvis Uptime
  introTitle: "Uptime status for Jarvis"
  introMessage: [jarvis.gtsu.org](https://jarvis.gtsu.org/)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
